
stages:
  - containers
  - builds
  - sanity_checks

.native_git_build_job:
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - export SCRATCH_DIR="/tmp/scratch"
    - export VROOT="$SCRATCH_DIR/vroot"
    - export LIBDIR="$VROOT/lib"
    - export LD_LIBRARY_PATH="$LIBDIR"
    - export PATH="$VROOT/bin:$PATH"
    - export PKG_CONFIG_PATH="$LIBDIR/pkgconfig"
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - cd libvirt
    - meson build -Ddriver_libvirtd=disabled "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - popd
    - rake build
    - rake test
    - if test "$DIST" != "skip" ; then rake package; fi

.native_git_build_job_prebuilt_env:
  extends:
    - .native_git_build_job
    - .gitlab_native_build_job_prebuilt_env

.native_git_build_job_local_env:
  extends:
    - .native_git_build_job
    - .gitlab_native_build_job_local_env

.native_build_job:
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - rake build
    - rake test
    - if test "$DIST" != "skip" ; then rake package; fi

.native_build_job_prebuilt_env:
  extends:
    - .native_build_job
    - .gitlab_native_build_job_prebuilt_env

.native_build_job_local_env:
  extends:
    - .native_build_job
    - .gitlab_native_build_job_local_env

.website:
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - rake rdoc
    - mv doc/site/ public
  artifacts:
    paths:
      - public

pages:
  extends:
    - .website
    - .gitlab_native_build_job_prebuilt_env
  needs:
    - job: x86_64-ubuntu-2204-container
      optional: true
  variables:
    NAME: ubuntu-2204

website_local_env:
  extends:
    - .website
    - .gitlab_native_build_job_local_env
  variables:
    IMAGE: docker.io/library/ubuntu:22.04
    NAME: ubuntu-2204


include: '/ci/gitlab.yml'
